version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mentorship-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mentorship-db

  user-service:
    build:
      context: .
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  mongo-data:
